name: Matix
on: push

jobs:
  node-verion:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_versions: [6, 8, 10]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: |
          node -v
          npm -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          npm -v
